/**
 * Executes a function which returns a promise, expecting it to reject.
 *
 * To assert that a synchronous function throws, use {@linkcode assertThrows}.
 *
 * @example
 * ```ts
 * import { assertRejects } from "@std/assert/assert-rejects";
 *
 * await assertRejects(async () => Promise.reject(new Error())); // Doesn't throw
 * await assertRejects(async () => console.log("Hello world")); // Throws
 * ```
 */ export declare function assertRejects(fn: () => PromiseLike<unknown>, msg?: string): Promise<unknown>;
/**
 * Executes a function which returns a promise, expecting it to reject.
 * If it does not, then it throws. An error class and a string that should be
 * included in the error message can also be asserted.
 *
 * To assert that a synchronous function throws, use {@linkcode assertThrows}.
 *
 * @example
 * ```ts
 * import { assertRejects } from "@std/assert/assert-rejects";
 *
 * await assertRejects(async () => Promise.reject(new Error()), Error); // Doesn't throw
 * await assertRejects(async () => Promise.reject(new Error()), SyntaxError); // Throws
 * ```
 */ export declare function assertRejects<E extends Error = Error>(fn: () => PromiseLike<unknown>, ErrorClass: new(...args: any[]) => E, msgIncludes?: string, msg?: string): Promise<E>;
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbImFzc2VydF9yZWplY3RzLnRzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiJBQUtBOzs7Ozs7Ozs7Ozs7Q0FZQyxHQUNELE9BQU8saUJBQVMsY0FDZCxVQUFVLFlBQVksT0FBTyxDQUFDLEVBQzlCLE1BQU0sTUFBTSxHQUNYLFFBQVEsT0FBTztBQUNsQjs7Ozs7Ozs7Ozs7Ozs7Q0FjQyxHQUNELE9BQU8saUJBQVMsY0FBYyxVQUFVLFFBQVEsT0FDOUMsVUFBVSxZQUFZLE9BQU8sQ0FBQyxFQUU5QixnQkFBaUIsR0FBRyxNQUFNLEdBQUcsT0FBTyxDQUFDLEVBQ3JDLGNBQWMsTUFBTSxFQUNwQixNQUFNLE1BQU0sR0FDWCxRQUFRIn0=