/**
 * Executes a function, expecting it to throw. If it does not, then it
 * throws.
 *
 * To assert that an asynchronous function rejects, use
 * {@linkcode assertRejects}.
 *
 * @example
 * ```ts
 * import { assertThrows } from "@std/assert/assert-throws";
 *
 * assertThrows(() => { throw new TypeError("hello world!"); }); // Doesn't throw
 * assertThrows(() => console.log("hello world!")); // Throws
 * ```
 */ export declare function assertThrows(fn: () => unknown, msg?: string): unknown;
/**
 * Executes a function, expecting it to throw. If it does not, then it
 * throws. An error class and a string that should be included in the
 * error message can also be asserted.
 *
 * To assert that an asynchronous function rejects, use
 * {@linkcode assertRejects}.
 *
 * @example
 * ```ts
 * import { assertThrows } from "@std/assert/assert-throws";
 *
 * assertThrows(() => { throw new TypeError("hello world!"); }, TypeError); // Doesn't throw
 * assertThrows(() => { throw new TypeError("hello world!"); }, RangeError); // Throws
 * ```
 */ export declare function assertThrows<E extends Error = Error>(fn: () => unknown, ErrorClass: new(...args: any[]) => E, msgIncludes?: string, msg?: string): E;
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbImFzc2VydF90aHJvd3MudHMiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IkFBS0E7Ozs7Ozs7Ozs7Ozs7O0NBY0MsR0FDRCxPQUFPLGlCQUFTLGFBQ2QsVUFBVSxPQUFPLEVBQ2pCLE1BQU0sTUFBTSxHQUNYLE9BQU87QUFDVjs7Ozs7Ozs7Ozs7Ozs7O0NBZUMsR0FDRCxPQUFPLGlCQUFTLGFBQWEsVUFBVSxRQUFRLE9BQzdDLFVBQVUsT0FBTyxFQUVqQixnQkFBaUIsR0FBRyxNQUFNLEdBQUcsT0FBTyxDQUFDLEVBQ3JDLGNBQWMsTUFBTSxFQUNwQixNQUFNLE1BQU0sR0FDWCJ9